spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route
          uri: lb://tonghua-authorization
#          uri: http://localhost:7777/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1